name: Build and push Docker image
description: Builds and pushes a Docker image
inputs:
    token:
        description: The token to use as password when logging into the GitHub Container Registry with Docker
        required: true
    tags:
        description: What tags to use for the Docker image
        required: false
        default: latest
runs:
    using: composite
    steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Login to Docker
          uses: docker/login-action@v3
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ inputs.token }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and Push
          uses: docker/bake-action@v6
          env:
              ACTIONS_RUNTIME_TOKEN: ${{ inputs.token }}
              ACTIONS_CACHE_SERVICE_V2: true
              TAGS: ${{ inputs.tags }}
          with:
              files: .docker/docker-bake.hcl
              push: true
