name: CI
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    ci:
        name: CI
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  cache: npm
                  node-version-file: .tool-versions
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Check formatting
              run: npm run format:check

            - name: Check linting
              run: npm run lint

            - name: Compile code
              run: npm run build

            - name: Run tests
              run: |
                  npx playwright install chromium
                  npm run test
