name: Build and Push Docker Image
on:
    workflow_dispatch:
permissions:
    contents: read
    packages: write
env:
    ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ACTIONS_CACHE_SERVICE_V2: true
jobs:
    build-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push
              uses: docker/bake-action@v6
              with:
                  files: .docker/docker-bake.hcl
                  push: true
