name: Release Published
on:
    release:
        types:
            - published
permissions:
    contents: read
    packages: write
jobs:
    docker-build:
        name: Build and push Docker image
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/dnd-mapp/dma-web-client
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=raw,value=latest,enabled=${{ !github.event.release.prerelease }}

            - name: Build and push Docker image
              uses: ./.github/actions/docker-build
              with:
                  tags: ${{ steps.meta.outputs.tags }}
                  token: ${{ secrets.GITHUB_TOKEN }}
